### ISSUE TITLE
frontend fails to build with `ERR_OSSL_EVP_UNSUPPORTED`

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhysInfo/altklausur-ausleihe#112]
Currently the frontend fails to build:

```
#0 2.238 To enable GQL files in ESLint, set the `pluginOptions.apollo.lintGQL` project option to `true` in `vue.config.js`. Put `false` to hide this message.
#0 2.238 You also need to install `eslint-plugin-graphql` and enable it in your ESLint configuration.
#0 2.551 Error: error:0308010C:digital envelope routines::unsupported
#0 2.551     at new Hash (node:internal/crypto/hash:71:19)
#0 2.551     at Object.createHash (node:crypto:133:10)
#0 2.551     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
#0 2.551     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
#0 2.551     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
#0 2.551     at /app/node_modules/webpack/lib/NormalModule.js:503:5
#0 2.551     at /app/node_modules/webpack/lib/NormalModule.js:358:12
#0 2.551     at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 2.551     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 2.551     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 2.551     at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 2.551     at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
#0 2.551     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
#0 2.551     at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
#0 2.551     at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
#0 2.551     at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
#0 4.489 /app/node_modules/loader-runner/lib/LoaderRunner.js:114
#0 4.489                        throw e;
#0 4.489                        ^
#0 4.489
#0 4.489 Error: error:0308010C:digital envelope routines::unsupported
#0 4.489     at new Hash (node:internal/crypto/hash:71:19)
#0 4.489     at Object.createHash (node:crypto:133:10)
#0 4.489     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
#0 4.489     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
#0 4.489     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
#0 4.489     at /app/node_modules/webpack/lib/NormalModule.js:503:5
#0 4.489     at /app/node_modules/webpack/lib/NormalModule.js:358:12
#0 4.489     at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 4.489     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 4.489     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 4.489     at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 4.489     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
#0 4.489     at /app/node_modules/cache-loader/dist/index.js:147:7
#0 4.489     at /app/node_modules/graceful-fs/graceful-fs.js:57:14
#0 4.489     at FSReqCallback.oncomplete (node:fs:197:23) {
#0 4.489   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#0 4.489   library: 'digital envelope routines',
#0 4.489   reason: 'unsupported',
#0 4.489   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#0 4.489 }
#0 4.489
#0 4.489 Node.js v18.12.1
------
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
```

**Comment by christian-heusel** [comment]
@TomTomRixRix can you maybe help with this? 😊

**Comment by christian-heusel** [comment]
According to this [answer on StackOverflow](https://stackoverflow.com/a/69665354) is caused by a webpack issue, tbh i dont know how to resolve it / bump webpack in out setup.

**Comment by TomTomRixRix** [comment]
So far I haven't heard of this issue, but I can have a look into it and see if I find a solution for our case.
